version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_and_test:
    docker:
      - image: openjdk:8-jdk-alpine
    steps:
      - checkout
      - run: ./gradlew build
      - persist_to_workspace:
          root: ./
          paths:
            - build/libs/springrest-0.0.1-SNAPSHOT.jar
            - Dockerfile
      - store_test_results:
          path: build/test-results


            # Orchestrate our job run sequence
workflows:
  spring_boot_cicd_workflow:
    jobs:
      - build_and_test