version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_and_test:
    docker:
      - image: openjdk:16-jdk-alpine
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run: ./gradlew build
      - persist_to_workspace:
          root: ./
          paths:
            - build/libs/springrest-0.0.1-SNAPSHOT.jar
            - Dockerfile
      - store_test_results:
          path: build/test-results
  package:
    docker:
      - image: docker:dind
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - attach_workspace:
          at: ./
      - run: docker build --iidfile image.txt -t registry.heroku.com/$HEROKU_APP_NAME/web:${CIRCLE_SHA1} .
      - run: docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
      - run: docker push registry.heroku.com/$HEROKU_APP_NAME/web:${CIRCLE_SHA1}
      - persist_to_workspace:
          root: ./
          paths:
            - image.txt
  deploy:
    docker:
      - image: docker:dind
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - attach_workspace:
          at: ./
      - run: apk add --no-cache curl
      
# Orchestrate our job run sequence
workflows:
  version: 2
  spring_boot_cicd_workflow:
    jobs:
      - build_and_test
      - package:
          requires:
            - build_and_test
      - deploy:
          requires:
            - package